server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: machine-doc-service
  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 64MB
  cloud:
    nacos:
      config:
        server-addr: ${machine.nacos.server-addr}
        username: ${machine.nacos.username}
        password: ${machine.nacos.password}
        file-extension: yaml
        namespace: MACHINE_${spring.profiles.active}
        group: MACHINE_GROUP
      discovery:
        server-addr: ${machine.nacos.server-addr}
        username: ${machine.nacos.username}
        password: ${machine.nacos.password}
        namespace: MACHINE_${spring.profiles.active}
        group: MACHINE_GROUP
  config:
    import:
      - nacos:machine.yaml?refreshEnabled=true
      - nacos:${spring.application.name}.yaml?refreshEnabled=true
