machine:
  mybatis:
    example: 1000

spring:
  # DataSource Config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${machine.datasource.host}:5432/${machine.datasource.schema}?tcpKeepAlive=true
    username: ${machine.datasource.username}
    password: ${machine.datasource.password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 最小空闲连接数
      minimum-idle: 2
      # 最大连接数
      maximum-pool-size: 8

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/com/machine/service/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.machine.service.**.dao.mapper.entity
  type-handlers-package: com.machine.starter.mybatis.handler
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: assign_id
      #字段策略
      insert-strategy: not_null
      update-strategy: not_null
      #驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false