machine:
  jwt:
    secret: XXX
  datasource:
    host: 127.0.0.1
    username: root
    password: root
  rabbitmq:
    host: localhost
    username: machine
    password: machine
  rocketmq:
    host: localhost
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis
  obs:
    minio-1:
      enable-storage: true
      access-key: root
      secret-key: root1234
      end-point: http://localhost:9000
      domain: http://localhost:9000
    huawei-obs-1:
      enable-storage: false
      access-key: XXX
      secret-key: XXX
      end-point: http://XXXXX.XXX.XX
      domain: http://XXXXX.XXX.XXX
    aliyun-oss-1:
      enable-storage: false
      access-key: XXX
      secret-key: XXX
      end-point: http://XXXXX.XXX.XX
      domain: http://XXXXX.XXX.XXX
  ai:
    deepseek:
      api-key: XXXXXX
      chat:
        options:
          model: deepseek-chat
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:8b
    dashscope:
      api-key: XXXXXX
      chat:
        options:
          model: qwen-plus

beisen:
  appKey: XXX
  appSecret: XXX

feiShu:
  message:
    appId: XXX
    appSecret: XXX