server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: machine-plugin-service
  cloud:
    nacos:
      config:
        server-addr: ${machine.nacos.server-addr}
        username: ${machine.nacos.username}
        password: ${machine.nacos.password}
        file-extension: yaml
        namespace: MACHINE_${spring.profiles.active}
        group: MACHINE_GROUP
      discovery:
        server-addr: ${machine.nacos.server-addr}
        username: ${machine.nacos.username}
        password: ${machine.nacos.password}
        namespace: MACHINE_${spring.profiles.active}
        group: MACHINE_GROUP
  config:
    import:
      - nacos:machine.yaml?refreshEnabled=true
      - nacos:${spring.application.name}.yaml?refreshEnabled=true


  # DataSource Config
  datasource:
    dynamic:
      strict: true
      datasource:
        yun_xi_cube_shop:
          url: jdbc:mysql://${machine.yunXiCubeShop.datasource.host}:3306/${machine.yunXiCubeShop.datasource.schema}?useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          username: ${machine.yunXiCubeShop.datasource.username}
          password: ${machine.yunXiCubeShop.datasource.password}
          driver-class-name: com.mysql.jdbc.Driver
        yun_xi_cube_user:
          url: jdbc:mysql://${machine.yunXiCubeUser.datasource.host}:3306/${machine.yunXiCubeUser.datasource.schema}?useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          username: ${machine.yunXiCubeUser.datasource.username}
          password: ${machine.yunXiCubeUser.datasource.password}
          driver-class-name: com.mysql.jdbc.Driver


#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/com/machine/service/*/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.machine.service.*.*.dao.mapper.entity
  type-handlers-package: com.machine.service.plugin.config.handler
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: assign_id
      #字段策略
      insert-strategy: not_null
      update-strategy: not_null
      #驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false