spring:
  ai:
    deepseek:
      api-key: ${machine.ai.deepseek.api-key}
      chat:
        options:
          model: ${machine.ai.deepseek.chat.options.model:deepseek-chat}
    ollama:
      base-url: ${machine.ai.ollama.base-url}
      chat:
        options:
          model: ${machine.ai.ollama.chat.options.model:deepseek-r1:8b}
    dashscope:
      api-key: ${machine.ai.dashscope.api-key}
      chat:
        options:
          model: ${machine.ai.dashscope.chat.options.model:qwen-plus}