server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
spring:
  main:
    allow-bean-definition-overriding: true
   
  application:
    name: machine-xxljob-server

  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  web:
    resources:
      static-locations: classpath:/static/

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
      new_builtin_class_resolver: safer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${machine.datasource.host}:3306/machine_xxljob?useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${machine.datasource.username}
    password: ${machine.datasource.password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      validation-timeout: 1000

  mail:
    host: smtp.qq.com
    port: 25
    username: machineswift@qq.com
    password: xxx
    from: xxx@qq.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  cloud:
    nacos:
      config:
        server-addr: ${machine.nacos.server-addr}
        username: ${machine.nacos.username}
        password: ${machine.nacos.password}
        file-extension: yaml
        namespace: MACHINE_${spring.profiles.active}
        group: MACHINE_GROUP
      discovery:
        server-addr: ${machine.nacos.server-addr}
        username: ${machine.nacos.username}
        password: ${machine.nacos.password}
        namespace: MACHINE_${spring.profiles.active}
        group: MACHINE_GROUP
  config:
    import:
      - nacos:machine.yaml?refreshEnabled=true
      - nacos:${spring.application.name}.yaml?refreshEnabled=true


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

### actuator
management:
  server:
    base-path: /actuator
  health:
    mail:
      enabled: false

xxl:
  job:
    timeout: 3
    accessToken: default_token
    i18n: zh_CN
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: 30


xxl-sso:
  token:
    key: xxl_job_login_token
    timeout: 604800000
  client:
    excluded:
      paths:
    login:
      path: /auth/login
