server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: machine-camunda-server
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 4096MB
  cloud:
    nacos:
      config:
        server-addr: ${machine.nacos.server-addr}
        username: ${machine.nacos.username}
        password: ${machine.nacos.password}
        file-extension: yaml
        namespace: MACHINE_${spring.profiles.active}
        group: MACHINE_GROUP
      discovery:
        server-addr: ${machine.nacos.server-addr}
        username: ${machine.nacos.username}
        password: ${machine.nacos.password}
        namespace: MACHINE_${spring.profiles.active}
        group: MACHINE_GROUP
  config:
    import:
      - nacos:machine.yaml?refreshEnabled=true
      - nacos:${spring.application.name}.yaml?refreshEnabled=true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${machine.datasource.host}:5432/machine_camunda?tcpKeepAlive=true
    username: ${machine.datasource.username}
    password: ${machine.datasource.password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 最小空闲连接数
      minimum-idle: 2
      # 最大连接数
      maximum-pool-size: 8

camunda:
  bpm:
    admin-user:
      id: root
      password: root
    filter:
      create: All tasks

cibseven:
  webclient:
    authentication:
      jwtSecret: 8Vy6wQTWKBZJY/cJbJQIFfYjBFj67snd3u5ETVeG7/jx4QJAQIHCGPvbRdjSpin+75q7EOIBJhBzDBhJt229miaK0vRm1eeGgvYpM28x1Xe9d22Xw7vpmApAhuN+ydf2dtU2p2UzjNYjsY37GIfoKLX97zVxLZwqpVt3Xm3b0w5IVo4ynyw920mjWThSh4k1wAwStvTJ9prCHIseOUBElrveRyCJn1fGU0GyWBINDx9aH8MlHtjAx9OklsxJ01eI759Ox1qouVcG0+4AVz651LdE9+ysnah6vjfwxWhkUG35yurhHqaDVUw1Mm6HEhJDgp9KFs6lPIZw6q4fCkfPWA==
      tokenValidMinutes: 60
      tokenProlongMinutes: 1440
    services:
      basePath: services/v1
    engineRest:
      url: http://localhost:8080